### ISSUE TITLE
Can't specify default grub entry

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#223]
According to https://github.com/rancher-sandbox/elemental/blob/main/config.yaml.example and by following https://rancher-sandbox.github.io/cOS-toolkit/docs/customizing/general_configuration/  I've tried to run an install with the following elemental config file:
```yaml
cosign: false
verify: false
install:
  grub-entry-name: "c3os"
  system:
    size: 2000
  recovery-system:
    size: 2000
upgrade:
  grub-entry-name: "c3os"
  recovery-system:
    size: 2000
  system:
    size: 2000
reset:
  grub-entry-name: "c3os"
  system:
    size: 2000
```
After install, the grub entry name wasn't applied, and indeed I could confirm that the grub env populated is with the default values:

```bash
cat /run/initramfs/cos-state/grub_oem_env 
# GRUB Environment Block
# WARNING: Do not edit this file by tools other than grub2-editenv!!!
default_menu_entry=cOS
```

By running upgrade with `--debug` can be seen that no string was loaded in the config.

Reproducible @ https://github.com/c3os-io/c3os/tree/updates
