### ISSUE TITLE
Refactor RunConfig struct

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#33]
as per discussion in https://github.com/rancher-sandbox/elemental-cli/pull/32#discussion_r776967358 there is room to improve how we are processing and organizing run time configuration details. This can be actually our way to read the manifest in the various phases ( e.g. https://github.com/rancher-sandbox/elemental/pull/160 )

Ideas:
* Define a set of generic configs and pass it to methods instead of moving around the whole `RunConfig`
* Defile a config struct isolated from flags and config files (no marshall/unmarshall) for each subcommand (aka `InstallConfig` struct)

See also:
 https://github.com/rancher-sandbox/elemental/blob/f1228393e3f342c07e265850b7f4c06f0c0128d3/pkg/types/v1/config.go#L47

**Comment by mudler** [comment]
I would add to move validation outside from `cmd` and be strict with the config itself, this way it is detached from the cli framework being used, and can be used in different contexts (validate a config file, for example)

**Comment by davidcassany** [comment]
Here a proposal from my side (covers install/upgrade/reset commands):

 ```yaml
install:
  # target is the only mandatory
  target: /dev/sda

  # basic disk configs for formatting
  firmware: efi|bios
  partitionTable: gpt|msdos

  # partitions setup, any missing value is taken from defaults
  partitions:
    oem:
      label:
      size:
      fs:
      flags:
    recovery:
      ...
    state:
      ...
    persistent:
      ...

  # recovery image should be squashed or not (eventual future feature)
  squashfsRecovery: true|false

  # format disk or not
  noFormat: true|false

  # use this iso as installation media (overwrites 'image' and 'recoveryImage' sources with iso contents)
  iso:

  # main OS image
  image:
    label:
    size:
    fs:
    source:
      type: dir|channel|package|image|file
      uri:

  # these are recovery image details, uses the same as 'image' if unset
  recoveryImage:
    label:
    size:
    fs:
    source:
      type: dir|channel|package|image|file
      uri:
    
upgrade:
  # upgrade system to this OS Image
  image:
    label:
    size:
    fs:
    source:
      type: dir|channel|package|image|file
      uri:

  # upgrade recovery image to this setup
  recoveryImage:
    label:
    size:
    fs:
    source:
      type: dir|channel|package|image|file
      uri:
    
reset:
  # reset to this OS image
  image:
    label:
    size:
    fs:
    source:
      type: dir|channel|package|image|file
      uri:

  # format persistent partition or not
  formatPersistent: true|false

# channel repositories used for channel sources
repositories:
  - name:
    uri:
    priority:
    type:

# attempt a cosign validation
cosign: true|false
cosignKey: myKey

# attempt a verify process
verify: true|false

# fail on cloud-init hooks errors
strict: true|false

# reboot/power off when done
reboot: true|false
poweroff: true|false
 ```

I would suggest to map this manifest to a RunConfig struct. Note the most minimalistic setup in yaml form would be:

```yaml
install:
  target: /some/device
```

And a common and simple setup for derivatives:

```yaml
install:
  target: /some/device
  image:
    source:
      # type is guessed from uri if missing
      uri: registry.org/some/image:latest

upgrade:
  image:
    source:
      uri: registry.org/some/image:latest
```

@mudler @Itxaka @mjura @ldevulder any ideas or comments regarding this manifest setup to describe installation and upgrade commands (reset command is anecdotic)?

**Comment by ldevulder** [comment]
Sounds interesting. I didn't played a lot with upgrade for now but looks good too. Maybe Harvester's guys can have more thought on this?

**Comment by mudler** [comment]
Few inline thoughts. It looks very good overall, just few non-obvious things from my side

```yaml
 # use this iso as installation media (overwrites 'image' and 'recoveryImage' sources with iso contents)
 iso:

 # main OS image
 image:
   label:
   size:
   fs:
   source:
     type: dir|channel|package|image|file
     uri:

 # these are recovery image details, uses the same as 'image' if unset
 recoveryImage:
   label:
   size:
   fs:
   source:
     type: dir|channel|package|image|file
     uri:
```

Here seems a bit inconsistent as there is a `iso` section in the middle that have no other option behind to expose. Maybe we can have a `system`/`recovery` block stanza instead which condense a bit the URI passed by, just an example:

```yaml
install:
  system:
    source: iso | image
    uri: "type://<path>" # the uri here would have to be parsed to define what is the source from. In case of iso, can be a label which defaults to COS_LABEL, for example.
    ....
  recovery:
  ..
```

so you can do e.g.:

```yaml
install:
  system:
    source: "iso" # that should be default, so nothing to really set 
upgrade:
   system:
    source: "container://registry...."
```

Note I changed `image` here and go for something more generic like `system`as it might be confusing on how we refer to `image` in the different contexts, but this is just an example so anything else would fit.

**Comment by davidcassany** [comment]
I like the `system`/`recovery` stanzas. I also like the idea of having sources defined on per scheme basis, that could also allow us to compact `--docker-image` and `--directory` flags to `--system-source` and easily allow us to introduce a  `--recovery-source` flag. However I do not see clear the `source: "iso"`, as this is not exactly a source type as others and it can't be easily referenced on per scheme type basis. Probably we could have something like:

```yaml
install:
  system:
    source: docker://my.registry.org/my/image:latest
  recovery:
    source: docker://my.registry.org/my/recovery:latest
```
and 

```yaml
install:
  install-iso: http://domain.org/my.iso
```
and assume `install-iso` (or `install-media`?) can overwrite system and recovery default sources.

Note the `install-iso` maps to `--iso` flag and it is unset by default. The default installation source is a local directory (where the live ISOs are mounted).
